PREFIX wiki: <http://wikidata.org/wiki/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?id ?description WHERE {
    VALUES ?id {
    values_list
    }
    ?id ?predicate ?description .
}
