file_path: data/genie-rebel/en_train.jsonl
start: 600000
end: 899999
maximum: 5000
task: contradiction_generation_v5
functions:
  - get_predicates_with_subject
  - get_predicates_with_object
  - get_subject_entities
  - get_object_entities
timeout: 20
recursion_limit: 100
